### ISSUE TITLE
Add missing translations for popup clinic

### ISSUE THREAD

**Issue by andrewpmk** [Vaccine-Hunters-Canada/VaxFinder-Frontend#110]
Add missing translations for popup clinic. Only translated in English and French right now. Update the spreadsheet at https://docs.google.com/spreadsheets/d/1MAtb1dFRullMkLM7i_pe8ATppxLQVvX3Enkcl4z_TfE/edit?usp=sharing

**Comment by luceliu** [comment]
added simplified chinese + spanish to the sheet. closed the draft PR cus accidentally branched off 106
