### ISSUE TITLE
Remove unneeded code from submission page. 

### ISSUE THREAD

**Issue by ericherscovich** [Vaccine-Hunters-Canada/VaxFinder-Frontend#175]
On the top of the form, the 24 hour notice is not needed anymore as we don't tweet.

<img width="1087" alt="Screen Shot 2021-12-26 at 11 01 46 PM" src="https://user-images.githubusercontent.com/71022385/147433069-8c69de5d-2eed-4b5f-923b-a45adab150bb.png">

Furthermore, the build your own tweet part in the Notes and Tweets is also no longer needed.

<img width="1045" alt="Screen Shot 2021-12-26 at 11 02 28 PM" src="https://user-images.githubusercontent.com/71022385/147433106-3ed12971-b1f4-4b00-b7d9-b99ad206f7fc.png">

**Comment by nulfrost** [comment]
Hey there, may I take this one on? Seems pretty straightforward

**Comment by ericherscovich** [comment]
Ya go for it! Just be aware you will need to branch instead of forking 😄

**Comment by nulfrost** [comment]
Alrighty, will do!
