### ISSUE TITLE
Allow for multiple vaccine types in self-reporting

### ISSUE THREAD

**Issue by ericherscovich** [Vaccine-Hunters-Canada/VaxFinder-Frontend#179]
On [the form](https://github.com/Vaccine-Hunters-Canada/VaxFinder-Frontend/blob/c44c5475d29e6cf51550b0fd58f675e55bc47b39/src/containers/RapidAppointment/RapidAppointment.tsx#L461) where we send vaccine availabilities, we currently only allow for one vaccine type to be selected. This is because our API can only accept a single vaccine type. This means if a pharmacy has Moderna and Pfizer, they have to create two different availabilities for this. We can make a change by sending one POST per vaccine type (as seen in the file linked) for the pharmacy. This means on the form, rather than a dropdown of vaccine type, it will be a checkbox. Then, we send one request per vaccine type they have selected. Since the backend returns all availabilities for a single pharmacy, I believe that our tagging system should pick it up on the frontend with no (or little) change.

**Comment by ryanwilsonperkin** [comment]
@ericherscovich should this also apply for the "PopUpForm" component? Seems like a pretty close copy of the "RapidAppointment" component

**Comment by ericherscovich** [comment]
PopUpForm is not really being used at all at the moment. Not quite sure what to do with it right now, might remove it, but regardless, I don't think there's any need to add it to the PopUpForm.

**Comment by ryanwilsonperkin** [comment]
Thanks Eric, I created an initial draft PR in #184 with the functionality. In the last PR, we discussed that we'll want to have the branches pushed to this repo so that CI can run properly on them, but it seems I can't yet push branches to this repository, maybe a missing write permission? If we can sort that out I'll re-open with a new branch under Vaccine-Hunters-Canada, or if not I can convert the draft to ready for review.

**Comment by ericherscovich** [comment]
Thanks! Yeah you need the write permission. Let me get on my computer and do this right now one second.

**Comment by ericherscovich** [comment]
You should have the email now for it. If you create the branch now it should pass CI.

**Comment by ryanwilsonperkin** [comment]
Dope, thanks! It's up now in #185
