### ISSUE TITLE
Update eligibility banner

### ISSUE THREAD

**Issue by picuron** [Vaccine-Hunters-Canada/VaxFinder-Frontend#36]

**Comment by picuron** [comment]
For the initial rollout, we will not have filtering by demographic. So, instead of removing to banner I will populate it with better info.

**Comment by MattAlp** [comment]
@picuron looks like we've made the banner more generic for the time being, should we close the issue or update the description?

**Comment by picuron** [comment]
Yeah, theres no super easy solution for displaying a persons eligibility based on their location, so just made it generic
