### ISSUE TITLE
Implement router for application

### ISSUE THREAD

**Issue by johnhok** [Vaccine-Hunters-Canada/VaxFinder-Frontend#41]
We should implement a router for the application so we can support standard routing between pages and have better deep linking support for various flows.

Recommend that we utilize: https://reactrouter.com/web/guides/quick-start

**Comment by chrisahardie** [comment]
👍 for this

To my mind, we would start with (at least) a couple routes:

`/` - shows form to submit postal code
`/search/:postalCode` - reads in postal code route param and performs the search

This will allow us to deep link directly to a search results screen for a particular postal code, so a direct URL could be given to someone, and the results screen could be bookmarked by the user for ease of use.

Thoughts @picuron @pleckey ? I know there were thoughts about using localStorage so people don't need to re-enter their postal code, but a bookmarked page might be another solution.

**Comment by pleckey** [comment]
I can’t 👍 this enough. Yes to deep linkable routes. LocalStorage was more
for the eligibility criteria and not postcode but we can always add a “Save
these criteria” checkbox to the criteria view, and prompt on these routes
if none found, to enable deep links which are a huge plus.

**Comment by chrisahardie** [comment]
Note to whomever implements this - please add a `MemoryRouter` to `AllTheProviders` in `testUtils.tsx` so our tests will continue to run :) Reach out if you have questions.
