### ISSUE TITLE
Update testing

### ISSUE THREAD

**Issue by shapesandobjects** [Vaccine-Hunters-Canada/VaxFinder-Frontend#63]
Check for:
* multiple search results returned (available + not available)
* no results return
* error returned
* 1 pharmacy card expanded to show hidden content

**Comment by jaycenca** [comment]
Hi @shapesandobjects , I'm interested in this task and I have some experiences working with testing. I saw the sample test cases in the Home.test.tsx file. Should we have a short conversations before I start? Thanks

**Comment by shapesandobjects** [comment]
> Hi @shapesandobjects , I'm interested in this task and I have some experiences working with testing. I familiarized with the sample test cases in the Home.test.tsx file. Should we have a short conversations before I start? Thanks

@jaycenca 
Sorry, didn't get to this comment earlier.
We just merged a big pile of work into the main branch, so work on this based off `main` can probably start at any time.  If you want to take a swing at this, feel free.  Can follow up with me if you've got any questions, and can go back and forth on a PR as appropriate.
A lot of this testing should probably be in `PharmacyList.test.tsx`, so that would be the best place to familiarize yourself with first.

**Comment by jaycenca** [comment]
Thank you. I will proceed to it immediately.

**Comment by jennygrahamjones** [comment]
Is this still an open issue? I'd like to help.

**Comment by ericherscovich** [comment]
Yeah totally, there are some files without tests and there are definitely tests that can be improved on and made a bit more thorough. If you want some more details feel free to send a message in the #fyi-discussion channel or DM me on Discord :)
