### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by andrewpmk** [Vaccine-Hunters-Canada/VaxFinder-Frontend#66]
I have created a pull request https://github.com/Vaccine-Hunters-Canada/VaxFinder-Frontend/pull/65 to switch the website between English and French. In the future we could offer more language options (if we can find volunteers to translate resource strings).

**Comment by chrisahardie** [comment]
Thanks @andrewpmk, issues lets us better audit why changes have been made to our code.
