### ISSUE TITLE
Allow for 3 letter postal input on front end

### ISSUE THREAD

**Issue by ericherscovich** [Vaccine-Hunters-Canada/VaxFinder-Frontend#84]

**Comment by chardielxr** [comment]
@ericherscovich Should we just constrain to the first three letters given the last three are useless? We would update the regex and probably wouldn't hurt to add the `maxlength=3` attribute to the input element.

**Comment by MattAlp** [comment]
@chardielxr this will also require updating the localization files to let users know to put in the first 3 characters of their postal code
