### ISSUE TITLE
Integrate eslint

### ISSUE THREAD

**Issue by chrisahardie** [Vaccine-Hunters-Canada/VaxFinder-Frontend#9]
This ticket is to introduce Eslint into the codebase in order to:

* enforce consistency
* enforce a code formatting style through Prettier
* catch issues

I've added a number of rules that I have found useful, but obviously the config can be customized.

**Comment by mittonface** [comment]
Relatedly, I'm a strong proponent of running prettier as a pre-commit hook so that we don't need to even worry about supporting devs through IDE setup.

**Comment by chardielxr** [comment]
I concur, and would think it warrants a ticket :)

I would suggest the hook runs:

* linting script
* tests
* build script

**Comment by chrisahardie** [comment]
Agree - prettier has been plugged into eslint, so the linting script will catch prettier issues. Ticket to create hook:

https://github.com/Vaccine-Hunters-Canada/VaxFinder-Frontend/issues/11
